// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/fakegps/v1/fakegps.proto

package fakegpsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimulationAction int32

const (
	SimulationAction_SIMULATION_ACTION_UNSPECIFIED SimulationAction = 0
	SimulationAction_SIMULATION_ACTION_START       SimulationAction = 1
	SimulationAction_SIMULATION_ACTION_STOP        SimulationAction = 2
	SimulationAction_SIMULATION_ACTION_PAUSE       SimulationAction = 3
	SimulationAction_SIMULATION_ACTION_RESUME      SimulationAction = 4
)

// Enum value maps for SimulationAction.
var (
	SimulationAction_name = map[int32]string{
		0: "SIMULATION_ACTION_UNSPECIFIED",
		1: "SIMULATION_ACTION_START",
		2: "SIMULATION_ACTION_STOP",
		3: "SIMULATION_ACTION_PAUSE",
		4: "SIMULATION_ACTION_RESUME",
	}
	SimulationAction_value = map[string]int32{
		"SIMULATION_ACTION_UNSPECIFIED": 0,
		"SIMULATION_ACTION_START":       1,
		"SIMULATION_ACTION_STOP":        2,
		"SIMULATION_ACTION_PAUSE":       3,
		"SIMULATION_ACTION_RESUME":      4,
	}
)

func (x SimulationAction) Enum() *SimulationAction {
	p := new(SimulationAction)
	*p = x
	return p
}

func (x SimulationAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulationAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fakegps_v1_fakegps_proto_enumTypes[0].Descriptor()
}

func (SimulationAction) Type() protoreflect.EnumType {
	return &file_proto_fakegps_v1_fakegps_proto_enumTypes[0]
}

func (x SimulationAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulationAction.Descriptor instead.
func (SimulationAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{0}
}

type DeviceStatus int32

const (
	DeviceStatus_DEVICE_STATUS_UNSPECIFIED  DeviceStatus = 0
	DeviceStatus_DEVICE_STATUS_IDLE         DeviceStatus = 1
	DeviceStatus_DEVICE_STATUS_ASSIGNED     DeviceStatus = 2
	DeviceStatus_DEVICE_STATUS_SIMULATING   DeviceStatus = 3
	DeviceStatus_DEVICE_STATUS_DISCONNECTED DeviceStatus = 4
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "DEVICE_STATUS_UNSPECIFIED",
		1: "DEVICE_STATUS_IDLE",
		2: "DEVICE_STATUS_ASSIGNED",
		3: "DEVICE_STATUS_SIMULATING",
		4: "DEVICE_STATUS_DISCONNECTED",
	}
	DeviceStatus_value = map[string]int32{
		"DEVICE_STATUS_UNSPECIFIED":  0,
		"DEVICE_STATUS_IDLE":         1,
		"DEVICE_STATUS_ASSIGNED":     2,
		"DEVICE_STATUS_SIMULATING":   3,
		"DEVICE_STATUS_DISCONNECTED": 4,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fakegps_v1_fakegps_proto_enumTypes[1].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_proto_fakegps_v1_fakegps_proto_enumTypes[1]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{1}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_StatusUpdate
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetStatusUpdate() *StatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_StatusUpdate struct {
	StatusUpdate *StatusUpdate `protobuf:"bytes,3,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_StatusUpdate) isAgentMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterResponse
	//	*ServerMessage_LocationUpdate
	//	*ServerMessage_SimulationCommand
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *ServerMessage) GetLocationUpdate() *LocationUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_LocationUpdate); ok {
			return x.LocationUpdate
		}
	}
	return nil
}

func (x *ServerMessage) GetSimulationCommand() *SimulationCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SimulationCommand); ok {
			return x.SimulationCommand
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,1,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type ServerMessage_LocationUpdate struct {
	LocationUpdate *LocationUpdate `protobuf:"bytes,2,opt,name=location_update,json=locationUpdate,proto3,oneof"`
}

type ServerMessage_SimulationCommand struct {
	SimulationCommand *SimulationCommand `protobuf:"bytes,3,opt,name=simulation_command,json=simulationCommand,proto3,oneof"`
}

func (*ServerMessage_RegisterResponse) isServerMessage_Payload() {}

func (*ServerMessage_LocationUpdate) isServerMessage_Payload() {}

func (*ServerMessage_SimulationCommand) isServerMessage_Payload() {}

// Sent by agent on initial connection.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceModel   string                 `protobuf:"bytes,3,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *RegisterRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        DeviceStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=fakegps.v1.DeviceStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{5}
}

func (x *StatusUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusUpdate) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *StatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Streamed from backend to agent with GPS coordinates.
type LocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         float32                `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`       // m/s
	Bearing       float32                `protobuf:"fixed32,5,opt,name=bearing,proto3" json:"bearing,omitempty"`   // degrees
	Accuracy      float32                `protobuf:"fixed32,6,opt,name=accuracy,proto3" json:"accuracy,omitempty"` // meters
	Altitude      float64                `protobuf:"fixed64,7,opt,name=altitude,proto3" json:"altitude,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,8,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdate) Reset() {
	*x = LocationUpdate{}
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdate) ProtoMessage() {}

func (x *LocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdate.ProtoReflect.Descriptor instead.
func (*LocationUpdate) Descriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{6}
}

func (x *LocationUpdate) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *LocationUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationUpdate) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationUpdate) GetBearing() float32 {
	if x != nil {
		return x.Bearing
	}
	return 0
}

func (x *LocationUpdate) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *LocationUpdate) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *LocationUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type SimulationCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        SimulationAction       `protobuf:"varint,1,opt,name=action,proto3,enum=fakegps.v1.SimulationAction" json:"action,omitempty"`
	SimulationId  string                 `protobuf:"bytes,2,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationCommand) Reset() {
	*x = SimulationCommand{}
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationCommand) ProtoMessage() {}

func (x *SimulationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fakegps_v1_fakegps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationCommand.ProtoReflect.Descriptor instead.
func (*SimulationCommand) Descriptor() ([]byte, []int) {
	return file_proto_fakegps_v1_fakegps_proto_rawDescGZIP(), []int{7}
}

func (x *SimulationCommand) GetAction() SimulationAction {
	if x != nil {
		return x.Action
	}
	return SimulationAction_SIMULATION_ACTION_UNSPECIFIED
}

func (x *SimulationCommand) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

var File_proto_fakegps_v1_fakegps_proto protoreflect.FileDescriptor

const file_proto_fakegps_v1_fakegps_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/fakegps/v1/fakegps.proto\x12\n" +
	"fakegps.v1\"\xcc\x01\n" +
	"\fAgentMessage\x129\n" +
	"\bregister\x18\x01 \x01(\v2\x1b.fakegps.v1.RegisterRequestH\x00R\bregister\x125\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.fakegps.v1.HeartbeatH\x00R\theartbeat\x12?\n" +
	"\rstatus_update\x18\x03 \x01(\v2\x18.fakegps.v1.StatusUpdateH\x00R\fstatusUpdateB\t\n" +
	"\apayload\"\xfe\x01\n" +
	"\rServerMessage\x12K\n" +
	"\x11register_response\x18\x01 \x01(\v2\x1c.fakegps.v1.RegisterResponseH\x00R\x10registerResponse\x12E\n" +
	"\x0flocation_update\x18\x02 \x01(\v2\x1a.fakegps.v1.LocationUpdateH\x00R\x0elocationUpdate\x12N\n" +
	"\x12simulation_command\x18\x03 \x01(\v2\x1d.fakegps.v1.SimulationCommandH\x00R\x11simulationCommandB\t\n" +
	"\apayload\"\x94\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12!\n" +
	"\fdevice_model\x18\x03 \x01(\tR\vdeviceModel\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"H\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"u\n" +
	"\fStatusUpdate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.fakegps.v1.DeviceStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xfa\x01\n" +
	"\x0eLocationUpdate\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x02R\x05speed\x12\x18\n" +
	"\abearing\x18\x05 \x01(\x02R\abearing\x12\x1a\n" +
	"\baccuracy\x18\x06 \x01(\x02R\baccuracy\x12\x1a\n" +
	"\baltitude\x18\a \x01(\x01R\baltitude\x12!\n" +
	"\ftimestamp_ms\x18\b \x01(\x03R\vtimestampMs\"n\n" +
	"\x11SimulationCommand\x124\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1c.fakegps.v1.SimulationActionR\x06action\x12#\n" +
	"\rsimulation_id\x18\x02 \x01(\tR\fsimulationId*\xa9\x01\n" +
	"\x10SimulationAction\x12!\n" +
	"\x1dSIMULATION_ACTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SIMULATION_ACTION_START\x10\x01\x12\x1a\n" +
	"\x16SIMULATION_ACTION_STOP\x10\x02\x12\x1b\n" +
	"\x17SIMULATION_ACTION_PAUSE\x10\x03\x12\x1c\n" +
	"\x18SIMULATION_ACTION_RESUME\x10\x04*\x9f\x01\n" +
	"\fDeviceStatus\x12\x1d\n" +
	"\x19DEVICE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DEVICE_STATUS_IDLE\x10\x01\x12\x1a\n" +
	"\x16DEVICE_STATUS_ASSIGNED\x10\x02\x12\x1c\n" +
	"\x18DEVICE_STATUS_SIMULATING\x10\x03\x12\x1e\n" +
	"\x1aDEVICE_STATUS_DISCONNECTED\x10\x042R\n" +
	"\fAgentService\x12B\n" +
	"\aConnect\x12\x18.fakegps.v1.AgentMessage\x1a\x19.fakegps.v1.ServerMessage(\x010\x01B[\n" +
	"\x18com.openfakegps.proto.v1P\x01Z=github.com/openfakegps/openfakegps/proto/fakegps/v1;fakegpsv1b\x06proto3"

var (
	file_proto_fakegps_v1_fakegps_proto_rawDescOnce sync.Once
	file_proto_fakegps_v1_fakegps_proto_rawDescData []byte
)

func file_proto_fakegps_v1_fakegps_proto_rawDescGZIP() []byte {
	file_proto_fakegps_v1_fakegps_proto_rawDescOnce.Do(func() {
		file_proto_fakegps_v1_fakegps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fakegps_v1_fakegps_proto_rawDesc), len(file_proto_fakegps_v1_fakegps_proto_rawDesc)))
	})
	return file_proto_fakegps_v1_fakegps_proto_rawDescData
}

var file_proto_fakegps_v1_fakegps_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_fakegps_v1_fakegps_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_fakegps_v1_fakegps_proto_goTypes = []any{
	(SimulationAction)(0),     // 0: fakegps.v1.SimulationAction
	(DeviceStatus)(0),         // 1: fakegps.v1.DeviceStatus
	(*AgentMessage)(nil),      // 2: fakegps.v1.AgentMessage
	(*ServerMessage)(nil),     // 3: fakegps.v1.ServerMessage
	(*RegisterRequest)(nil),   // 4: fakegps.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 5: fakegps.v1.RegisterResponse
	(*Heartbeat)(nil),         // 6: fakegps.v1.Heartbeat
	(*StatusUpdate)(nil),      // 7: fakegps.v1.StatusUpdate
	(*LocationUpdate)(nil),    // 8: fakegps.v1.LocationUpdate
	(*SimulationCommand)(nil), // 9: fakegps.v1.SimulationCommand
}
var file_proto_fakegps_v1_fakegps_proto_depIdxs = []int32{
	4, // 0: fakegps.v1.AgentMessage.register:type_name -> fakegps.v1.RegisterRequest
	6, // 1: fakegps.v1.AgentMessage.heartbeat:type_name -> fakegps.v1.Heartbeat
	7, // 2: fakegps.v1.AgentMessage.status_update:type_name -> fakegps.v1.StatusUpdate
	5, // 3: fakegps.v1.ServerMessage.register_response:type_name -> fakegps.v1.RegisterResponse
	8, // 4: fakegps.v1.ServerMessage.location_update:type_name -> fakegps.v1.LocationUpdate
	9, // 5: fakegps.v1.ServerMessage.simulation_command:type_name -> fakegps.v1.SimulationCommand
	1, // 6: fakegps.v1.StatusUpdate.status:type_name -> fakegps.v1.DeviceStatus
	0, // 7: fakegps.v1.SimulationCommand.action:type_name -> fakegps.v1.SimulationAction
	2, // 8: fakegps.v1.AgentService.Connect:input_type -> fakegps.v1.AgentMessage
	3, // 9: fakegps.v1.AgentService.Connect:output_type -> fakegps.v1.ServerMessage
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_fakegps_v1_fakegps_proto_init() }
func file_proto_fakegps_v1_fakegps_proto_init() {
	if File_proto_fakegps_v1_fakegps_proto != nil {
		return
	}
	file_proto_fakegps_v1_fakegps_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_StatusUpdate)(nil),
	}
	file_proto_fakegps_v1_fakegps_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterResponse)(nil),
		(*ServerMessage_LocationUpdate)(nil),
		(*ServerMessage_SimulationCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fakegps_v1_fakegps_proto_rawDesc), len(file_proto_fakegps_v1_fakegps_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fakegps_v1_fakegps_proto_goTypes,
		DependencyIndexes: file_proto_fakegps_v1_fakegps_proto_depIdxs,
		EnumInfos:         file_proto_fakegps_v1_fakegps_proto_enumTypes,
		MessageInfos:      file_proto_fakegps_v1_fakegps_proto_msgTypes,
	}.Build()
	File_proto_fakegps_v1_fakegps_proto = out.File
	file_proto_fakegps_v1_fakegps_proto_goTypes = nil
	file_proto_fakegps_v1_fakegps_proto_depIdxs = nil
}
